### ISSUE TITLE
Google Music and YouTube scrobbling broken

### ISSUE THREAD

**Issue by HEdingfield** [web-scrobbler/web-scrobbler#1576]
### Expected behavior
Google Music and YouTube should scrobble music.

### Current behavior
It's not scrobbling. Instead when I click on the extension it says "Play some music to get started".

### Possible solution
Tried disabling / re-enabling extension, and also uninstalling / re-installing but didn't work.

### Steps to reproduce (for bugs)

1. Start Google Music Play or YouTube.
2. Play a song.
3. Notice that it's not scrobbling.

FYI: this link is broken... https://github.com/web-scrobbler/web-scrobbler/wiki/How-to-debug-the-extension

### Context
Trying to scrobble my music.

### Environment

* Version used: 2.3.5
* Browser name and version: Chrome 64.0.3282.140 (Official Build) (64-bit)

**Comment by HEdingfield** [comment]
Thanks for the corrected link on how to debug. That should be updated in the bug creation pre-filled text.

My logs are here:
https://pastebin.mozilla.org/9077934

**Comment by alexesprit** [comment]
> FYI: this link is broken...

Thanks, I've updated URL in all documents.

> My logs are here:
> pastebin.mozilla.org/9077934

Looks like, this issue is related to new Chrome update.

```
_generated_background_page.html:1 Unchecked runtime.lastError while running tabs.executeScript: This page cannot be scripted due to an ExtensionsSettings policy.
    at injectWorker (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:62:19)
    at chrome.tabs.sendMessage (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:74:5)
```
I don't know what is this ExtensionsSettings policy, but if this feature could be turned off, you can try to do that, as a temporary solution. Will install new Chrome and take a look into that.

**Comment by OwnageIsMagic** [comment]
https://support.google.com/chrome/a/answer/7517525
`runtime_blocked_hosts`

**Comment by johnlunney** [comment]
FWIW, Bandcamp scrobbling still works (same Chrome version)

**Comment by HEdingfield** [comment]
Interestingly, confirmed that it works for me in Windows with Chrome 64.0.3282.167 (Official Build) (64-bit). However, it's still not working for me in Linux with Chrome 64.0.3282.186 (Official Build) (64-bit).

**Comment by HEdingfield** [comment]
Here are logs that first play a song in Soundcloud, then Youtube.

<details>
<summary>Debug log</summary>
```
Loaded for the first time, injecting the scripts
inject.js:61 Injecting vendor/jquery.min.js
inject.js:61 Injecting core/content/reactor.js
inject.js:61 Injecting core/content/filter.js
inject.js:61 Injecting core/content/util.js
inject.js:61 Injecting core/content/connector.js
inject.js:61 Injecting connectors/soundcloud.js
inject.js:61 Injecting core/content/starter.js
controller.js:558 Tab 1102: Created controller for SoundCloud connector
controller.js:558 Tab 1102: New song detected: {
  "track": "Meizja",
  "artist": "Permanent Starlight",
  "album": null,
  "uniqueID": "https://soundcloud.com/permanent-starlight/meizja",
  "duration": 334,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://i1.sndcdn.com/artworks-000248589279-dhpcl1-large.jpg"
}
scrobbleService.js:89 Send "get info" request: 1
baseScrobbler.js:492 Last.fm: track.getinfo response:
<?xml version="1.0" encoding="UTF-8" ?>
<lfm status="ok"><track><name>Meizja</name>
<url>https://www.last.fm/music/Permanent+Starlight/_/Meizja</url>
<duration>0</duration>
<streamable fulltrack="0">0</streamable>
<listeners>1</listeners>
<playcount>21</playcount>
<artist><name>Permanent Starlight</name>
<url>https://www.last.fm/music/Permanent+Starlight</url>
</artist>
<userplaycount>21</userplaycount>
<userloved>1</userloved>
<toptags></toptags>
</track>
</lfm>

coverartarchive.js:29 Using local/parsed artwork
controller.js:558 Tab 1102: Song finished processing: {
  "parsed": {
    "artist": "Permanent Starlight",
    "track": "Meizja",
    "album": null,
    "uniqueID": "https://soundcloud.com/permanent-starlight/meizja",
    "duration": 334,
    "currentTime": null,
    "isPlaying": true,
    "trackArt": "https://i1.sndcdn.com/artworks-000248589279-dhpcl1-large.jpg"
  },
  "processed": {
    "artist": "Permanent Starlight",
    "track": "Meizja",
    "album": "",
    "duration": null
  },
  "metadata": {
    "userloved": true,
    "startTimestamp": 1519674335,
    "connector": {
      "label": "SoundCloud",
      "matches": [
        "*://soundcloud.com/*"
      ],
      "js": [
        "connectors/soundcloud.js"
      ]
    },
    "artistThumbUrl": "",
    "artistUrl": "https://www.last.fm/music/Permanent+Starlight",
    "trackUrl": "https://www.last.fm/music/Permanent+Starlight/_/Meizja",
    "albumUrl": ""
  },
  "flags": {
    "isProcessed": true,
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false
  }
}
controller.js:558 Tab 1102: The song will be scrobbled in 167 seconds
scrobbleService.js:105 Send "now playing" request: 1
baseScrobbler.js:492 Last.fm: track.updatenowplaying response:
<?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <nowplaying>
    <track corrected="0">Meizja</track>
    <artist corrected="0">Permanent Starlight</artist>
    <album corrected="0"></album>
    <albumArtist corrected="0"></albumArtist>
    <ignoredMessage code="0"></ignoredMessage>
  </nowplaying>
</lfm>

controller.js:558 Tab 1102: Song set as now playing
controller.js:558 Tab 1102: isPlaying state changed to false
main.js:324 Tab 1102: Remove controller for SoundCloud connector
inject.js:37 Loaded for the first time, injecting the scripts
inject.js:61 Injecting vendor/jquery.min.js
inject.js:61 Injecting core/content/reactor.js
5Unchecked runtime.lastError while running tabs.executeScript: This page cannot be scripted due to an ExtensionsSettings policy.
    at injectWorker (<URL>)
    at chrome.tabs.sendMessage (<URL>)
inject.js:61 Injecting core/content/filter.js
30Unchecked runtime.lastError while running tabs.executeScript: This page cannot be scripted due to an ExtensionsSettings policy.
    at Object.injectWorker [as callback] (<URL>)
inject.js:61 Injecting core/content/util.js
inject.js:61 Injecting core/content/connector.js
inject.js:61 Injecting connectors/youtube.js
inject.js:61 Injecting core/content/starter.js
controller.js:558 Tab 1110: Created controller for YouTube connector
inject.js:37 Loaded for the first time, injecting the scripts
inject.js:61 Injecting vendor/jquery.min.js
inject.js:37 Loaded for the first time, injecting the scripts
inject.js:61 Injecting vendor/jquery.min.js
inject.js:37 Loaded for the first time, injecting the scripts
inject.js:61 Injecting vendor/jquery.min.js
3inject.js:61 Injecting core/content/reactor.js
3inject.js:61 Injecting core/content/filter.js
3inject.js:61 Injecting core/content/util.js
3inject.js:61 Injecting core/content/connector.js
3inject.js:61 Injecting connectors/youtube.js
3inject.js:61 Injecting core/content/starter.js
main.js:324 Tab 1110: Remove controller for YouTube connector
controller.js:558 Tab 1110: Created controller for YouTube connector
main.js:324 Tab 1110: Remove controller for YouTube connector
controller.js:558 Tab 1110: Created controller for YouTube connector
main.js:324 Tab 1110: Remove controller for YouTube connector
controller.js:558 Tab 1110: Created controller for YouTube connector
inject.js:37 Loaded for the first time, injecting the scripts
inject.js:61 Injecting vendor/jquery.min.js
inject.js:61 Injecting core/content/reactor.js
inject.js:61 Injecting core/content/filter.js
inject.js:61 Injecting core/content/util.js
inject.js:61 Injecting core/content/connector.js
inject.js:61 Injecting connectors/youtube.js
inject.js:61 Injecting core/content/starter.js
main.js:324 Tab 1110: Remove controller for YouTube connector
controller.js:558 Tab 1110: Created controller for YouTube connector
main.js:324 Tab 1110: Remove controller for YouTube connector
```
</details>

**Comment by inverse** [comment]
Do we need to set a CSP?

https://developer.chrome.com/extensions/contentSecurityPolicy

**Comment by oldtasty** [comment]
Experiencing failure to scrobble on YouTube and Google Play Music using the Chrome Web Scrobbler extension.

**Google Chrome:** 65.0.3325.162 (Official Build) (64-bit)
**Revision:** 5d04e9e9c8ce31bee0923a8c326a7e9e19c492a3-refs/branch-heads/3325@{#695}
**OS:** Linux
**JavaScript:** V8 6.5.254.36
**Flash:** 29.0.0.113

The scrobbler is working for Spotify, Soundcloud and Bandcamp.

**Comment by HEdingfield** [comment]
This is still an issue for me and it's a major bummer. Any bandwidth / ideas on how to fix this? Does it seem like the CSP that @inverse mentioned could address this?

**Comment by alexesprit** [comment]
@HEdingfield I searched for "ExtensionSettings policy" and found out the policies are configured by administators:

> Applies to Windows users who sign in to a managed account on Chrome Browser.

> As an administrator, you can automatically install Chrome apps and extensions on users' computers. You can also control which apps or extensions users can install. You set the default policies for all apps and extensions. Then, if you want to customize policies for specific apps or extensions, you can override your defaults.

Do you try to launch the extension on work or somewhere else?

Interesting that it happens with Google services only.

**Comment by HEdingfield** [comment]
Yeah, I think you're on to something! This is occurring on my work computers. Maybe it's restricted because of that.

**Comment by alexesprit** [comment]
Thanks for the information.
