### ISSUE TITLE
Chrome: Spotify stopped working

### ISSUE THREAD

**Issue by EvHaus** [web-scrobbler/web-scrobbler#2986]
**Describe the bug**
Seems like Spotify track identification is not working anymore for me in the Chrome extension.

**How to reproduce**
1. Install and configure Web Scrobbler for Chrome
2. Go to https://open.spotify.com/album/7m34sN0AfFHJfOBVEMttKu
3. Play the track
4. BUG: The track is not recognized

**Expected behavior**
The track should be recognized and submitted to Last.fm

**Screenshots**
Track is not recognized notification comes up. I also noticed the UI for the popup is really narrow and broken.

<img width="171" alt="Screen Shot 2021-09-15 at 7 54 31 AM" src="https://user-images.githubusercontent.com/226640/133457314-33a902ee-33d3-4bb6-9ab5-879c60f36d2d.png">

**Debug logs**

```
Web Scrobbler: Setting up observer
util.js:521 Web Scrobbler: Element '.Root__now-playing-bar' is missing
debugLog @ util.js:521
guc3-spclient.spotify.com/remote-config-resolver/v2/configs/platforms/web/clients/web-player/property-sets/63a5909cc1066cbc?installation-id=02c50df67e73a5108491b0e7732219d6&fetch-type=delayed:1 Failed to load resource: the server responded with a status of 404 ()
util.js:521 Web Scrobbler: Used '.Root__now-playing-bar' to watch changes.
util.js:521 Web Scrobbler: isPlaying state changed to false
util.js:521 Web Scrobbler: {
  "track": "Wait for You (Matrix & Futurebound Remix)",
  "artist": "Tom Walker, Matrix & Futurebound",
  "album": "Wait for You (Matrix & Futurebound Remix)",
  "albumArtist": null,
  "uniqueID": null,
  "duration": 220,
  "currentTime": 93,
  "isPlaying": false,
  "trackArt": "https://i.scdn.co/image/ab67616d000048519e5e23e9bdf4cacc107b0604",
  "isPodcast": false,
  "originUrl": "https://open.spotify.com/album/7m34sN0AfFHJfOBVEMttKu"
}
web-player.1538a3b6.js:1 Uncaught (in promise) DUPLICATE_REQUEST_ERROR: DUPLICATE_REQUEST_ERROR: Already sent this request (GET::https://api.spotify.com/v1/me/albums/contains::{"ids":"7m34sN0AfFHJfOBVEMttKu"})
    at p.e.onBeforeSend (https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1671681)
    at p.send (https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1668825)
    at https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1299155
    at OU (https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1298219)
    at wU (https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1298961)
    at https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1300821
    at LU (https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1300858)
    at https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1301861
    at Array.map (<anonymous>)
    at DU (https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1301832)
    at fV.onBatchChanged (https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1455631)
    at hD.onUpdate (https://open.scdn.co/cdn/build/web-player/web-player.1538a3b6.js:1:1252715)
    at r (https://open.scdn.co/cdn/build/web-player/vendor~web-player.9ae30de9.js:1:198209)
util.js:521 Web Scrobbler: isPlaying state changed to true
util.js:521 Web Scrobbler: isPlaying state changed to false
```

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Chrome
-   Extension version: 2.45.0

**Comment by jaccarmac** [comment]
The width issue and a workaround are in #2983. I can't duplicate the issue on that page: The track name comes back as "Wait for You (Matrix & Futurebound Remix)".
