### ISSUE TITLE
spotify not scrobbling

### ISSUE THREAD

**Issue by fillycolt** [web-scrobbler/web-scrobbler#3907]
**Describe the bug**
spotify no longer is supported by the web scrobbler even though the connector is toggled on

**How to reproduce**
1. Go to spotify
2. Click on any song
3. check last.fm page or extension
4. no scrobbles show/extension says it is not supported on that page

**Expected behavior**
spotify should be connected and the songs should be scrobbling on last.fm

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.
not 100% if this is right, but this is what i found following those steps:
Web Scrobbler: storage.LastFM = null
main.js:1 Web Scrobbler: storage.LibreFM = null
main.js:1 Web Scrobbler: storage.ListenBrainz = null
main.js:1 Web Scrobbler: storage.Maloja = null
main.js:1 Web Scrobbler: storage.Options = {
  "disabledConnectors": "[hidden]",
  "forceRecognize": false,
  "scrobbleEditedTracksOnly": false,
  "scrobblePercent": 50,
  "scrobblePodcasts": true,
  "scrobbleRecognizedTracks": true,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": false
}
main.js:1 Web Scrobbler: storage.Connectors = {
  "YouTube": {
    "enableGetTrackInfoFromYtMusic": false,
    "scrobbleEntertainmentOnly": false,
    "scrobbleMusicOnly": false,
    "scrobbleMusicRecognisedOnly": false
  }
}
main.js:1 Web Scrobbler: storage.ConnectorsOverrideOptions = null
8main.js:1 Error: Could not establish connection. Receiving end does not exist.
    at ge (main.js:1:9102)
(anonymous) @ main.js:1
5main.js:1 Error: Could not establish connection. Receiving end does not exist.
    at ge (main.js:1:9102)
(anonymous) @ main.js:1
Promise.catch (async)
gt @ main.js:1
le @ main.js:1
await in le (async)
js @ main.js:5
await in js (async)
Yt @ main.js:5

**Environment (please complete the following information)**
-   OS: windows 10
-   Browser: chrome
-   Extension version: 3.0.13

**Additional context**
the last time it worked was july 18th

**Comment by IronPurple10** [comment]
I have this problem also in Chrome. But Web Scrobbler is working through Opera.

**Comment by yayuyokitano** [comment]
Apologies for the delay, had a lot of IRL stuff and going through issue backlog now. Unable to repro this. Is the issue still occurring?

Given the timing of this issue, I suspect it mightve just been a situation where chrome broke the extension in an update and a page refresh was needed to sync it back up.

**Comment by rob9315** [comment]
I think it's fixed now? closing, but feel free to reopen or make a new issue if this is still a problem
