### ISSUE TITLE
I can't connect to Last.fm

### ISSUE THREAD

**Issue by allanaleal** [web-scrobbler/web-scrobbler#4759]
Hello.

I started to use the app two days ago and everything was fine but today, when I was listening to music, I notice that my scrobbles wasn't counting anymore. I tried to see the accounts and its said that it isn't connected. So I press to connect, but it didn't work. I tried uninstall and then install back but still didn't work. I went to my last.fm to see the connections, there said the app was still connected to the Web Scrobbler, but still it didn't work the scrobbling, so I disconnect there and get back to the Web Scrobbler and still nothing.

Please, I want a light on how to proceed here.

Regards.

**Comment by XanderStrike** [comment]
I've also been dealing with this today.

Disabling my ad-blocker allowed me to authenticate the extension with last.fm, however I still can't scrobble.

Extension shows:
<img width="371" alt="image" src="https://github.com/web-scrobbler/web-scrobbler/assets/1565303/07817567-da41-43c0-9907-41059abf5b78">

Dev console:
<img width="554" alt="image" src="https://github.com/web-scrobbler/web-scrobbler/assets/1565303/ee363b25-26c8-47ae-8334-ab75922a08f0">

I've tried with both youtube music and amazon music.

**Comment by inverse** [comment]
I'm unable to reproduce the issue at the moment.

Are you able to provide more detailed logs?

Check our guide on how to here: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by XanderStrike** [comment]
Sure, this is opening a tab, playing one song in full and part of another, neither were scrobbled:

<details>
<summary> clickarino </summary>

```
music_polymer_inlined_html.js:4812 LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
main.js:1 Web Scrobbler: Injected connectors/youtube-music-dom-inject.js
main.js:1 Web Scrobbler: Successfully loaded YouTube Music connector
main.js:1 Web Scrobbler: Controller: Created controller for YouTube Music connector
main.js:1 Web Scrobbler: Setting up observer
main.js:1 Web Scrobbler: Used 'ytmusic-player-bar' to watch changes.
310Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.Understand this warning
music.youtube.com/:1 requestStorageAccessFor: Permission denied.Understand this error
music.youtube.com/:1 requestStorageAccessFor: Permission denied.Understand this error
music.youtube.com/:1 requestStorageAccessFor: Permission denied.Understand this error
main.js:1 Web Scrobbler: Controller: New song detected: {
  "track": "Mississippi (Instrumental)",
  "artist": "Blockhead",
  "album": "Mississippi (Instrumental)",
  "albumArtist": null,
  "uniqueID": "wOwoGHroark",
  "duration": 235,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://lh3.googleusercontent.com/DETx7Zid3iWEMRFVdI0UIX08r1e7yiuukz8CsGM8AwV8n1Vx3IPXCo_3PRhsBiOZkon3Bilz0ITzmeet_g=w544-h544-l90-rj",
  "isPodcast": false,
  "originUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kI8Xc9EhfhaCsG9dol1KAxLvLuKIU7xkw",
  "scrobblingDisallowedReason": null
}
main.js:1 Web Scrobbler: Using local/parsed artwork
main.js:1 Web Scrobbler: Controller: Song finished processing: {
  "parsed": {
    "track": "Mississippi (Instrumental)",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": "Mississippi (Instrumental)",
    "duration": 235,
    "uniqueID": "wOwoGHroark",
    "currentTime": null,
    "isPlaying": true,
    "trackArt": "https://lh3.googleusercontent.com/DETx7Zid3iWEMRFVdI0UIX08r1e7yiuukz8CsGM8AwV8n1Vx3IPXCo_3PRhsBiOZkon3Bilz0ITzmeet_g=w544-h544-l90-rj",
    "isPodcast": false,
    "originUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kI8Xc9EhfhaCsG9dol1KAxLvLuKIU7xkw",
    "scrobblingDisallowedReason": null
  },
  "processed": {
    "track": "Mississippi (Instrumental)",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": "Mississippi (Instrumental)",
    "duration": 235
  },
  "noRegex": {
    "track": "Mississippi (Instrumental)",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": "Mississippi (Instrumental)",
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isRegexEditedByUser": {
      "track": false,
      "artist": false,
      "album": false,
      "albumArtist": false
    },
    "isAlbumFetched": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false,
    "hasBlockedTag": false,
    "isLovedInService": null,
    "finishedProcessing": true
  },
  "metadata": {
    "startTimestamp": 1718414147,
    "label": "YouTube Music"
  },
  "connector": {
    "label": "YouTube Music",
    "matches": [
      "*://music.youtube.com/*"
    ],
    "js": "youtube-music.js",
    "id": "youtube-music"
  }
}
main.js:1 Web Scrobbler: Controller: The song will be scrobbled in 117 seconds
main.js:1 Web Scrobbler: Controller: The song will be repeated in 235 seconds
main.js:1 Web Scrobbler: Controller: Song isn't set as now playing
main.js:1 Uncaught (in promise) Error: Invalid result: e
    at xe (main.js:1:46121)
xe @ main.js:1
await in xe (async)
(anonymous) @ main.js:2
(anonymous) @ main.js:2
Show 3 more frames
Show lessUnderstand this error
main.js:1 Web Scrobbler: Controller: New song detected: {
  "track": "Mississippi (Instrumental)",
  "artist": "Blockhead",
  "album": "Mississippi (Instrumental)",
  "albumArtist": null,
  "uniqueID": "P0RGzC6mImU",
  "duration": 235,
  "currentTime": 234,
  "isPlaying": true,
  "trackArt": "https://lh3.googleusercontent.com/DETx7Zid3iWEMRFVdI0UIX08r1e7yiuukz8CsGM8AwV8n1Vx3IPXCo_3PRhsBiOZkon3Bilz0ITzmeet_g=w544-h544-l90-rj",
  "isPodcast": false,
  "originUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kI8Xc9EhfhaCsG9dol1KAxLvLuKIU7xkw",
  "scrobblingDisallowedReason": null
}
main.js:1 Uncaught (in promise) Error: Notification ID is not set
    at xe (main.js:1:46121)
xe @ main.js:1
Show 1 more frame
Show lessUnderstand this error
main.js:1 Web Scrobbler: Controller: New song detected: {
  "track": "Insomniac Olympics",
  "artist": "Blockhead",
  "album": null,
  "albumArtist": null,
  "uniqueID": "P0RGzC6mImU",
  "duration": 307,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://lh3.googleusercontent.com/fzAyiAYp7H-QPfhrUH-VTEevMJezC0iBEksBDYon8nVoIac0IIrRvTPBO0B8O9BlSqIWFmp--9nRRJVXag=w544-h544-l90-rj",
  "isPodcast": false,
  "originUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kI8Xc9EhfhaCsG9dol1KAxLvLuKIU7xkw",
  "scrobblingDisallowedReason": null
}
main.js:1 Uncaught (in promise) Error: Notification ID is not set
    at xe (main.js:1:46121)
xe @ main.js:1
Show 1 more frame
Show lessUnderstand this error
main.js:1 Web Scrobbler: Using local/parsed artwork
main.js:1 Web Scrobbler: Controller: Song finished processing: {
  "parsed": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": null,
    "duration": 307,
    "uniqueID": "P0RGzC6mImU",
    "currentTime": null,
    "isPlaying": true,
    "trackArt": "https://lh3.googleusercontent.com/fzAyiAYp7H-QPfhrUH-VTEevMJezC0iBEksBDYon8nVoIac0IIrRvTPBO0B8O9BlSqIWFmp--9nRRJVXag=w544-h544-l90-rj",
    "isPodcast": false,
    "originUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kI8Xc9EhfhaCsG9dol1KAxLvLuKIU7xkw",
    "scrobblingDisallowedReason": null
  },
  "processed": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": null,
    "duration": 307
  },
  "noRegex": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": null,
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isRegexEditedByUser": {
      "track": false,
      "artist": false,
      "album": false,
      "albumArtist": false
    },
    "isAlbumFetched": false,
    "isValid": false,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false,
    "hasBlockedTag": false,
    "isLovedInService": null,
    "finishedProcessing": true
  },
  "metadata": {
    "startTimestamp": 1718414382,
    "label": "YouTube Music"
  },
  "connector": {
    "label": "YouTube Music",
    "matches": [
      "*://music.youtube.com/*"
    ],
    "js": "youtube-music.js",
    "id": "youtube-music"
  }
}
main.js:1 Web Scrobbler: Controller: The song will be scrobbled in 154 seconds
main.js:1 Web Scrobbler: Controller: The song will be repeated in 307 seconds
main.js:1 Web Scrobbler: Using local/parsed artwork
main.js:1 Web Scrobbler: Controller: Song finished processing: {
  "parsed": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": null,
    "duration": 307,
    "uniqueID": "P0RGzC6mImU",
    "currentTime": 1,
    "isPlaying": true,
    "trackArt": "https://lh3.googleusercontent.com/fzAyiAYp7H-QPfhrUH-VTEevMJezC0iBEksBDYon8nVoIac0IIrRvTPBO0B8O9BlSqIWFmp--9nRRJVXag=w544-h544-l90-rj",
    "isPodcast": false,
    "originUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kI8Xc9EhfhaCsG9dol1KAxLvLuKIU7xkw",
    "scrobblingDisallowedReason": null
  },
  "processed": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "duration": 307
  },
  "noRegex": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isRegexEditedByUser": {
      "track": false,
      "artist": false,
      "album": false,
      "albumArtist": false
    },
    "isAlbumFetched": true,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false,
    "hasBlockedTag": false,
    "isLovedInService": null,
    "finishedProcessing": true
  },
  "metadata": {
    "startTimestamp": 1718414382,
    "label": "YouTube Music"
  },
  "connector": {
    "label": "YouTube Music",
    "matches": [
      "*://music.youtube.com/*"
    ],
    "js": "youtube-music.js",
    "id": "youtube-music"
  }
}
main.js:1 Web Scrobbler: Controller: The song will be scrobbled in 154 seconds
main.js:1 Web Scrobbler: Controller: The song will be repeated in 307 seconds
main.js:1 Web Scrobbler: Controller: Song isn't set as now playing
main.js:1 Web Scrobbler: Controller: New song detected: {
  "track": "Insomniac Olympics",
  "artist": "Blockhead",
  "album": "Music By Cavelight",
  "albumArtist": null,
  "uniqueID": "P0RGzC6mImU",
  "duration": 307,
  "currentTime": 2,
  "isPlaying": true,
  "trackArt": "https://lh3.googleusercontent.com/fzAyiAYp7H-QPfhrUH-VTEevMJezC0iBEksBDYon8nVoIac0IIrRvTPBO0B8O9BlSqIWFmp--9nRRJVXag=w544-h544-l90-rj",
  "isPodcast": false,
  "originUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kI8Xc9EhfhaCsG9dol1KAxLvLuKIU7xkw",
  "scrobblingDisallowedReason": null
}
main.js:1 Uncaught (in promise) Error: Notification ID is not set
    at xe (main.js:1:46121)
xe @ main.js:1
Show 1 more frame
Show lessUnderstand this error
main.js:1 Web Scrobbler: Using local/parsed artwork
main.js:1 Web Scrobbler: Controller: Song finished processing: {
  "parsed": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": "Music By Cavelight",
    "duration": 307,
    "uniqueID": "P0RGzC6mImU",
    "currentTime": 2,
    "isPlaying": true,
    "trackArt": "https://lh3.googleusercontent.com/fzAyiAYp7H-QPfhrUH-VTEevMJezC0iBEksBDYon8nVoIac0IIrRvTPBO0B8O9BlSqIWFmp--9nRRJVXag=w544-h544-l90-rj",
    "isPodcast": false,
    "originUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kI8Xc9EhfhaCsG9dol1KAxLvLuKIU7xkw",
    "scrobblingDisallowedReason": null
  },
  "processed": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": "Music By Cavelight",
    "duration": 307
  },
  "noRegex": {
    "track": "Insomniac Olympics",
    "artist": "Blockhead",
    "albumArtist": null,
    "album": "Music By Cavelight",
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isRegexEditedByUser": {
      "track": false,
      "artist": false,
      "album": false,
      "albumArtist": false
    },
    "isAlbumFetched": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false,
    "hasBlockedTag": false,
    "isLovedInService": null,
    "finishedProcessing": true
  },
  "metadata": {
    "startTimestamp": 1718414383,
    "label": "YouTube Music"
  },
  "connector": {
    "label": "YouTube Music",
    "matches": [
      "*://music.youtube.com/*"
    ],
    "js": "youtube-music.js",
    "id": "youtube-music"
  }
}
main.js:1 Web Scrobbler: Controller: The song will be scrobbled in 154 seconds
main.js:1 Web Scrobbler: Controller: The song will be repeated in 307 seconds
main.js:1 Web Scrobbler: Controller: Song isn't set as now playing
main.js:1 Web Scrobbler: Controller: isPlaying state changed to false
```

</details>

**Comment by inverse** [comment]
Thanks that helps narrow down the problem. It looks to be when we're trying to tell last.fm to set the song as playing. 

Is there anymore insights from the service worker?  e.g. https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-the-background-script

This might help understand what last.fm is reporting.

**Comment by wonpiria** [comment]
facing the same issue. I disconnected last fm from the extension and website but now when I click to connect the accounts, nothing happens. I don't have any adblockers enabled

**Comment by XanderStrike** [comment]
Just noticed this still isn't working 3 weeks later. Here's the logs you asked for @inverse 

```

D @ main.js:1
signOut @ main.js:4
await in signOut (async)
signOut @ main.js:6
getSession @ main.js:6
await in getSession (async)
bindAllScrobblers @ main.js:6
await in bindAllScrobblers (async)
Wa @ main.js:6
fn @ main.js:6
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:6 song changed in tab 863438032
main.js:6 {parsed: {…}, noRegex: {…}, processed: {…}, metadata: {…}, flags: {…}, …}
main.js:1 Error: Could not establish connection. Receiving end does not exist.
    at G (main.js:1:9173)
(anonymous) @ main.js:1
Promise.catch (async)
Ys @ main.js:1
ye @ main.js:1
await in ye (async)
Bt @ main.js:6
await in Bt (async)
er @ main.js:6
fn @ main.js:6
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Libre.fm: auth.getsession response:
{
  "error": 14,
  "message": "This token has not yet been authorised"
}
main.js:1 Libre.fm: Failed to trade token for session
D @ main.js:1
debugLog @ main.js:4
getSession @ main.js:4
await in getSession (async)
bindAllScrobblers @ main.js:6
await in bindAllScrobblers (async)
$a @ main.js:6
fn @ main.js:6
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 ListenBrainz: no data
D @ main.js:1
debugLog @ main.js:4
getSession @ main.js:6
await in getSession (async)
bindAllScrobblers @ main.js:6
await in bindAllScrobblers (async)
$a @ main.js:6
fn @ main.js:6
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 No data in storage
D @ main.js:1
signOut @ main.js:4
await in signOut (async)
signOut @ main.js:6
getSession @ main.js:6
await in getSession (async)
bindAllScrobblers @ main.js:6
await in bindAllScrobblers (async)
$a @ main.js:6
fn @ main.js:6
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:6 changed mode to Error in tab 863438032
main.js:1 Error: Could not establish connection. Receiving end does not exist.
    at G (main.js:1:9173)
(anonymous) @ main.js:1
Promise.catch (async)
Ys @ main.js:1
ye @ main.js:1
await in ye (async)
Bt @ main.js:6
await in Bt (async)
Xa @ main.js:6
fn @ main.js:6
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
3main.js:1 Error: Could not establish connection. Receiving end does not exist.
    at G (main.js:1:9173)
```

**Comment by XanderStrike** [comment]
Actually looks like my issue was related to: https://github.com/web-scrobbler/web-scrobbler/issues/4783
